# Generated by Django 4.2.10 on 2024-03-25 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_rename_faculty_name_faculty_name'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistants', to='university.faculty'),
        ),
        migrations.RemoveField(
            model_name='professor',
            name='specialization',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_code',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='specialization',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
