# Generated by Django 5.0.3 on 2024-03-20 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentcourse',
            options={'verbose_name': 'student course'},
        ),
    ]
