# Generated by Django 4.2.10 on 2024-04-07 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_alter_course_corequisites_alter_course_major_and_more'),
        ('users', '0002_assistant_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='faculty',
            field=models.ForeignKey(help_text='Assistant To Faculty Relation', on_delete=django.db.models.deletion.CASCADE, related_name='assistants', to='university.faculty'),
        ),
        migrations.AlterField(
            model_name='assistant',
            name='major',
            field=models.ForeignKey(help_text='Assistant To Major Relation', on_delete=django.db.models.deletion.CASCADE, related_name='assistants', to='university.major'),
        ),
        migrations.AlterField(
            model_name='assistant',
            name='user',
            field=models.OneToOneField(help_text='Assistant To User Relation', on_delete=django.db.models.deletion.CASCADE, related_name='assistant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='professor',
            name='major',
            field=models.ForeignKey(help_text='Professor To Major Relation', on_delete=django.db.models.deletion.CASCADE, related_name='professors', to='university.major'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='rank',
            field=models.CharField(choices=[('I', 'Instructor'), ('A1', 'Assistant Professor'), ('A2', 'Associate Professor'), ('P', 'Professor')], help_text="Professor's Rank ('I', 'Instructor'),('A1', 'Assistant Professor'), ('A2', 'Associate Professor'), ('P', 'Professor')", max_length=2),
        ),
        migrations.AlterField(
            model_name='professor',
            name='specialization',
            field=models.CharField(help_text="Professor's Specialization", max_length=50),
        ),
        migrations.AlterField(
            model_name='professor',
            name='user',
            field=models.OneToOneField(help_text='Professor To User Relation', on_delete=django.db.models.deletion.CASCADE, related_name='professor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_semester',
            field=models.ForeignKey(help_text='Student To Semester Relation', on_delete=django.db.models.deletion.CASCADE, related_name='students', to='university.semester'),
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_year',
            field=models.PositiveIntegerField(help_text='Admission Year in Integer format 2023 2024 ...'),
        ),
        migrations.AlterField(
            model_name='student',
            name='advisor',
            field=models.ForeignKey(blank=True, help_text='Student To Advisor Relation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='users.professor'),
        ),
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.ForeignKey(help_text='Student To Major Relation', on_delete=django.db.models.deletion.CASCADE, related_name='students', to='university.major'),
        ),
        migrations.AlterField(
            model_name='student',
            name='military_status',
            field=models.BooleanField(default=False, help_text='Mandatory Military Status'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(help_text='User To Student Relation', on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Date of birth in date format : YYYY-MM-DD or YYYY/MM/DD', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Required. Inform a valid email address.', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], help_text='M for Male/F for Female', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='national_id',
            field=models.CharField(help_text='10 digit national id', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(help_text='Required (09) 9-digit phone', max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_code',
            field=models.CharField(help_text='Unique user code that varies based on user type', max_length=255, unique=True),
        ),
    ]
