# Generated by Django 5.0.3 on 2024-03-20 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_rename_courseoffering_semestercourse_and_more'),
        ('users', '0002_alter_studentcourse_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcourse',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentcourse',
            name='course',
        ),
        migrations.RemoveField(
            model_name='studentcourse',
            name='term_taken',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='StudentCourse',
        ),
    ]
