# Generated by Django 5.0.3 on 2024-03-20 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_rename_courseoffering_semestercourse_and_more'),
        ('users', '0003_remove_studentcourse_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_admission', models.PositiveIntegerField()),
                ('admission_semester', models.CharField(max_length=20)),
                ('grade', models.FloatField()),
                ('military_status', models.BooleanField(default=False)),
                ('remaining_semesters', models.IntegerField()),
                ('advisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.professor')),
                ('completed_courses', models.ManyToManyField(blank=True, related_name='completed_by', to='university.approvedcourse')),
                ('courses_in_progress', models.ManyToManyField(blank=True, related_name='in_progress_by', to='university.approvedcourse')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='university.faculty')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='university.major')),
                ('student_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
