# Generated by Django 4.2.10 on 2024-03-28 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCorrectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Accepted'), ('R', 'Rejected'), ('I', 'In Progress')], max_length=1, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseRegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Accepted'), ('R', 'Rejected'), ('I', 'In Progress')], max_length=1, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DefermentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='deferment_files')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmergencyWithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Accepted'), ('R', 'Rejected'), ('I', 'In Progress')], max_length=1, null=True)),
                ('text', models.TextField()),
                ('response', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReconsiderationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Accepted'), ('R', 'Rejected'), ('I', 'In Progress')], max_length=1, null=True)),
                ('text', models.TextField()),
                ('response', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentCourseParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('R', 'Registered'), ('A', 'Added'), ('D', 'Dropped')], max_length=1)),
                ('semester_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_semester_course', to='university.semestercourse')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_semester_course', to='university_requests.courseregistrationrequest')),
            ],
        ),
        migrations.CreateModel(
            name='SemesterWithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Accepted'), ('R', 'Rejected'), ('I', 'In Progress')], max_length=1, null=True)),
                ('text', models.TextField()),
                ('response', models.TextField()),
                ('count_semester', models.BooleanField(default=False)),
                ('semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semester_withdrawal_requests', to='university.semester')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
