# Generated by Django 4.2.10 on 2024-04-07 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCorrectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Accepted'), ('R', 'Rejected'), ('I', 'In Progress')], default='I', help_text="Request Status ('A', 'Accepted'), ('R', 'Rejected'), ('I', 'In Progress')", max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseRegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Accepted'), ('R', 'Rejected'), ('I', 'In Progress')], default='I', help_text="Request Status ('A', 'Accepted'), ('R', 'Rejected'), ('I', 'In Progress')", max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DefermentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Request File', upload_to='deferment_files')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmergencyWithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Accepted'), ('R', 'Rejected'), ('I', 'In Progress')], default='I', help_text="Request Status ('A', 'Accepted'), ('R', 'Rejected'), ('I', 'In Progress')", max_length=1)),
                ('text', models.TextField(help_text='Request Text')),
                ('response', models.TextField(help_text='Response Text')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReconsiderationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Accepted'), ('R', 'Rejected'), ('I', 'In Progress')], default='I', help_text="Request Status ('A', 'Accepted'), ('R', 'Rejected'), ('I', 'In Progress')", max_length=1)),
                ('text', models.TextField(help_text='Request Text')),
                ('response', models.TextField(help_text='Response Text')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentCourseParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('R', 'Registered'), ('A', 'Added'), ('D', 'Dropped'), ('I', 'In Progress')], default='I', help_text="Request Status ('A', 'Accepted'), ('R', 'Rejected'), ('I', 'In Progress')", max_length=1)),
                ('course', models.ForeignKey(help_text='Request To Courses Relation', on_delete=django.db.models.deletion.CASCADE, related_name='student_semester_course', to='university.semestercourse')),
                ('student', models.ForeignKey(help_text='Request To Student Relation', on_delete=django.db.models.deletion.CASCADE, related_name='student_semester_course', to='university_requests.courseregistrationrequest')),
            ],
        ),
        migrations.CreateModel(
            name='SemesterWithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Accepted'), ('R', 'Rejected'), ('I', 'In Progress')], default='I', help_text="Request Status ('A', 'Accepted'), ('R', 'Rejected'), ('I', 'In Progress')", max_length=1)),
                ('text', models.TextField(help_text='Request Text')),
                ('response', models.TextField(help_text='Response Text')),
                ('count_semester', models.BooleanField(default=False, help_text='Whether To Count Semesters Or Not')),
                ('semester', models.ForeignKey(help_text='Request To Semester Relation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semester_withdrawal_requests', to='university.semester')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
