# Generated by Django 4.2.10 on 2024-04-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_requests', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentcourseparticipant',
            old_name='semester_course',
            new_name='course',
        ),
        migrations.AlterField(
            model_name='coursecorrectionrequest',
            name='status',
            field=models.CharField(choices=[('A', 'Accepted'), ('R', 'Rejected'), ('I', 'In Progress')], default='I', max_length=1),
        ),
        migrations.AlterField(
            model_name='courseregistrationrequest',
            name='status',
            field=models.CharField(choices=[('A', 'Accepted'), ('R', 'Rejected'), ('I', 'In Progress')], default='I', max_length=1),
        ),
        migrations.AlterField(
            model_name='emergencywithdrawalrequest',
            name='status',
            field=models.CharField(choices=[('A', 'Accepted'), ('R', 'Rejected'), ('I', 'In Progress')], default='I', max_length=1),
        ),
        migrations.AlterField(
            model_name='reconsiderationrequest',
            name='status',
            field=models.CharField(choices=[('A', 'Accepted'), ('R', 'Rejected'), ('I', 'In Progress')], default='I', max_length=1),
        ),
        migrations.AlterField(
            model_name='semesterwithdrawalrequest',
            name='status',
            field=models.CharField(choices=[('A', 'Accepted'), ('R', 'Rejected'), ('I', 'In Progress')], default='I', max_length=1),
        ),
        migrations.AlterField(
            model_name='studentcourseparticipant',
            name='status',
            field=models.CharField(choices=[('R', 'Registered'), ('A', 'Added'), ('D', 'Dropped'), ('I', 'In Progress')], default='I', max_length=1),
        ),
    ]
