# Generated by Django 4.2.10 on 2024-04-07 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_alter_course_corequisites_alter_course_major_and_more'),
        ('users', '0003_alter_assistant_faculty_alter_assistant_major_and_more'),
        ('university_requests', '0003_rename_semester_course_studentcourseparticipant_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecorrectionrequest',
            name='added_courses',
            field=models.ManyToManyField(help_text='Request To Courses Relation', related_name='correction_add_requests', to='university.semestercourse'),
        ),
        migrations.AlterField(
            model_name='coursecorrectionrequest',
            name='dropped_courses',
            field=models.ManyToManyField(help_text='Request To Courses Relation', related_name='correction_drop_requests', to='university.semestercourse'),
        ),
        migrations.AlterField(
            model_name='coursecorrectionrequest',
            name='status',
            field=models.CharField(choices=[('A', 'Accepted'), ('R', 'Rejected'), ('I', 'In Progress')], default='I', help_text="Request Status ('A', 'Accepted'), ('R', 'Rejected'), ('I', 'In Progress')", max_length=1),
        ),
        migrations.AlterField(
            model_name='coursecorrectionrequest',
            name='student',
            field=models.ForeignKey(help_text='Request To Student Relation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='users.student'),
        ),
        migrations.AlterField(
            model_name='courseregistrationrequest',
            name='courses',
            field=models.ManyToManyField(help_text='Request To Courses Relation', related_name='registration_requests', through='university_requests.StudentCourseParticipant', to='university.semestercourse'),
        ),
        migrations.AlterField(
            model_name='courseregistrationrequest',
            name='status',
            field=models.CharField(choices=[('A', 'Accepted'), ('R', 'Rejected'), ('I', 'In Progress')], default='I', help_text="Request Status ('A', 'Accepted'), ('R', 'Rejected'), ('I', 'In Progress')", max_length=1),
        ),
        migrations.AlterField(
            model_name='courseregistrationrequest',
            name='student',
            field=models.ForeignKey(help_text='Request To Student Relation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='users.student'),
        ),
        migrations.AlterField(
            model_name='defermentrequest',
            name='faculty',
            field=models.ForeignKey(help_text='Request To Faculty Relation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deferment_requests', to='university.faculty'),
        ),
        migrations.AlterField(
            model_name='defermentrequest',
            name='file',
            field=models.FileField(help_text='Request File', upload_to='deferment_files'),
        ),
        migrations.AlterField(
            model_name='defermentrequest',
            name='semester',
            field=models.ForeignKey(help_text='Request To Semester Relation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deferment_requests', to='university.semester'),
        ),
        migrations.AlterField(
            model_name='defermentrequest',
            name='student',
            field=models.ForeignKey(help_text='Request To Student Relation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='users.student'),
        ),
        migrations.AlterField(
            model_name='emergencywithdrawalrequest',
            name='course',
            field=models.ForeignKey(help_text='Request To Courses Relation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_withdrawal_requests', to='university.semestercourse'),
        ),
        migrations.AlterField(
            model_name='emergencywithdrawalrequest',
            name='response',
            field=models.TextField(help_text='Response Text'),
        ),
        migrations.AlterField(
            model_name='emergencywithdrawalrequest',
            name='status',
            field=models.CharField(choices=[('A', 'Accepted'), ('R', 'Rejected'), ('I', 'In Progress')], default='I', help_text="Request Status ('A', 'Accepted'), ('R', 'Rejected'), ('I', 'In Progress')", max_length=1),
        ),
        migrations.AlterField(
            model_name='emergencywithdrawalrequest',
            name='student',
            field=models.ForeignKey(help_text='Request To Student Relation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='users.student'),
        ),
        migrations.AlterField(
            model_name='emergencywithdrawalrequest',
            name='text',
            field=models.TextField(help_text='Request Text'),
        ),
        migrations.AlterField(
            model_name='reconsiderationrequest',
            name='course',
            field=models.ForeignKey(help_text='Request To Courses Relation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reconsideration_requests', to='university.semestercourse'),
        ),
        migrations.AlterField(
            model_name='reconsiderationrequest',
            name='response',
            field=models.TextField(help_text='Response Text'),
        ),
        migrations.AlterField(
            model_name='reconsiderationrequest',
            name='status',
            field=models.CharField(choices=[('A', 'Accepted'), ('R', 'Rejected'), ('I', 'In Progress')], default='I', help_text="Request Status ('A', 'Accepted'), ('R', 'Rejected'), ('I', 'In Progress')", max_length=1),
        ),
        migrations.AlterField(
            model_name='reconsiderationrequest',
            name='student',
            field=models.ForeignKey(help_text='Request To Student Relation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='users.student'),
        ),
        migrations.AlterField(
            model_name='reconsiderationrequest',
            name='text',
            field=models.TextField(help_text='Request Text'),
        ),
        migrations.AlterField(
            model_name='semesterwithdrawalrequest',
            name='count_semester',
            field=models.BooleanField(default=False, help_text='Whether To Count Semesters Or Not'),
        ),
        migrations.AlterField(
            model_name='semesterwithdrawalrequest',
            name='response',
            field=models.TextField(help_text='Response Text'),
        ),
        migrations.AlterField(
            model_name='semesterwithdrawalrequest',
            name='semester',
            field=models.ForeignKey(help_text='Request To Semester Relation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semester_withdrawal_requests', to='university.semester'),
        ),
        migrations.AlterField(
            model_name='semesterwithdrawalrequest',
            name='status',
            field=models.CharField(choices=[('A', 'Accepted'), ('R', 'Rejected'), ('I', 'In Progress')], default='I', help_text="Request Status ('A', 'Accepted'), ('R', 'Rejected'), ('I', 'In Progress')", max_length=1),
        ),
        migrations.AlterField(
            model_name='semesterwithdrawalrequest',
            name='student',
            field=models.ForeignKey(help_text='Request To Student Relation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='users.student'),
        ),
        migrations.AlterField(
            model_name='semesterwithdrawalrequest',
            name='text',
            field=models.TextField(help_text='Request Text'),
        ),
        migrations.AlterField(
            model_name='studentcourseparticipant',
            name='course',
            field=models.ForeignKey(help_text='Request To Courses Relation', on_delete=django.db.models.deletion.CASCADE, related_name='student_semester_course', to='university.semestercourse'),
        ),
        migrations.AlterField(
            model_name='studentcourseparticipant',
            name='status',
            field=models.CharField(choices=[('R', 'Registered'), ('A', 'Added'), ('D', 'Dropped'), ('I', 'In Progress')], default='I', help_text="Request Status ('A', 'Accepted'), ('R', 'Rejected'), ('I', 'In Progress')", max_length=1),
        ),
        migrations.AlterField(
            model_name='studentcourseparticipant',
            name='student',
            field=models.ForeignKey(help_text='Request To Student Relation', on_delete=django.db.models.deletion.CASCADE, related_name='student_semester_course', to='university_requests.courseregistrationrequest'),
        ),
    ]
