version: '3.9'

services:
  redis:
    container_name: redis
    image: "redis:alpine"
    ports:
      - "6379:6379"

  django:
    container_name: django
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/home/app/web/
    ports:
      - "8001:8000"
    env_file:
      - ./.env
    depends_on:
      - redis

  celery:
    container_name: celery
    build:
      context: .
    command: celery --app=config worker -l INFO
    volumes:
      - .:/home/app/web/
    env_file:
      - ./.env
    depends_on:
      - redis
