version: '3.9'

services:
#  postgres:
#    container_name: postgres

  redis:
    container_name: redis
    image: "redis:alpine"
    ports:
      - "6379:6379"

  django:
    container_name: django
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8001:8000
    env_file:
      - ./.env
    depends_on:
      - redis

  celery:
    container_name: celery
    build:
      context: .
    command: celery --app=config worker -l INFO
    volumes:
      - .:/usr/src/app/
    env_file:
      - ./.env
    depends_on:
      - redis
