# Generated by Django 4.2.10 on 2024-03-23 23:11

from django.db import migrations, models
import users.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCorrectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_code', models.CharField(default=users.utils.generate_code, editable=False, max_length=10, unique=True)),
                ('approval_status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CourseRegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_code', models.CharField(default=users.utils.generate_code, editable=False, max_length=10, unique=True)),
                ('approval_status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DefermentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_code', models.CharField(default=users.utils.generate_code, editable=False, max_length=10, unique=True)),
                ('deferment_file', models.FileField(upload_to='deferment_files')),
                ('issuing_authority', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyWithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_code', models.CharField(default=users.utils.generate_code, editable=False, max_length=10, unique=True)),
                ('request_outcome', models.CharField(max_length=20)),
                ('student_explanation', models.TextField()),
                ('educational_deputy_explanation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ReconsiderationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_code', models.CharField(default=users.utils.generate_code, editable=False, max_length=10, unique=True)),
                ('reconsideration_text', models.TextField()),
                ('reconsideration_response', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SemesterWithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_code', models.CharField(default=users.utils.generate_code, editable=False, max_length=10, unique=True)),
                ('withdrawal_outcome', models.CharField(max_length=50)),
                ('student_explanation', models.TextField()),
                ('educational_deputy_explanation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_status', models.CharField(max_length=20)),
                ('grade', models.FloatField()),
            ],
        ),
    ]
