# Generated by Django 5.0.3 on 2024-03-20 07:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('university', '0003_rename_courseoffering_semestercourse_and_more'),
        ('users', '0003_remove_studentcourse_student_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_admission', models.PositiveIntegerField()),
                ('admission_semester', models.CharField(max_length=20)),
                ('grade', models.FloatField()),
                ('military_status', models.BooleanField(default=False)),
                ('remaining_semesters', models.IntegerField()),
                ('advisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.professor')),
                ('completed_courses', models.ManyToManyField(blank=True, related_name='completed_by', to='university.approvedcourse')),
                ('courses_in_progress', models.ManyToManyField(blank=True, related_name='in_progress_by', to='university.approvedcourse')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='university.faculty')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='university.major')),
                ('student_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SemesterWithdrawalRequest',
            fields=[
                ('request_code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('withdrawal_outcome', models.CharField(max_length=50)),
                ('student_explanation', models.TextField()),
                ('educational_deputy_explanation', models.TextField()),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='university.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student_dash.student')),
            ],
        ),
        migrations.CreateModel(
            name='ReconsiderationRequest',
            fields=[
                ('request_code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reconsideration_text', models.TextField()),
                ('reconsideration_response', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='university.approvedcourse')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student_dash.student')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyWithdrawalRequest',
            fields=[
                ('request_code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_outcome', models.CharField(max_length=20)),
                ('student_explanation', models.TextField()),
                ('educational_deputy_explanation', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='university.approvedcourse')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student_dash.student')),
            ],
        ),
        migrations.CreateModel(
            name='DefermentRequest',
            fields=[
                ('request_code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deferment_file', models.FileField(upload_to='deferment_files')),
                ('issuing_authority', models.CharField(max_length=100)),
                ('academic_semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='university.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student_dash.student')),
            ],
        ),
        migrations.CreateModel(
            name='CourseRegistrationRequest',
            fields=[
                ('request_code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('approval_status', models.CharField(max_length=20)),
                ('requested_courses', models.ManyToManyField(blank=True, related_name='course_request', to='university.approvedcourse')),
                ('requesting_student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student_dash.student')),
            ],
        ),
        migrations.CreateModel(
            name='CourseCorrectionRequest',
            fields=[
                ('request_code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('approval_status', models.CharField(max_length=20)),
                ('added_courses', models.ManyToManyField(related_name='added_by', to='university.approvedcourse')),
                ('dropped_courses', models.ManyToManyField(related_name='dropped_by', to='university.approvedcourse')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student_dash.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_status', models.CharField(max_length=20)),
                ('grade', models.FloatField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='university.approvedcourse')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_dash.student')),
                ('term_taken', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='university.semester')),
            ],
        ),
    ]
