# Generated by Django 4.2.10 on 2024-03-25 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_rename_faculty_name_faculty_name'),
        ('users', '0002_alter_assistant_faculty_and_more'),
        ('student_dash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecorrectionrequest',
            name='added_courses',
            field=models.ManyToManyField(related_name='correction_add_requests', to='university.semestercourse'),
        ),
        migrations.AddField(
            model_name='coursecorrectionrequest',
            name='dropped_courses',
            field=models.ManyToManyField(related_name='correction_drop_requests', to='university.semestercourse'),
        ),
        migrations.AddField(
            model_name='coursecorrectionrequest',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='users.student'),
        ),
        migrations.AddField(
            model_name='courseregistrationrequest',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='users.student'),
        ),
        migrations.AddField(
            model_name='defermentrequest',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deferment_requests', to='university.faculty'),
        ),
        migrations.AddField(
            model_name='defermentrequest',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deferment_requests', to='university.semester'),
        ),
        migrations.AddField(
            model_name='defermentrequest',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='users.student'),
        ),
        migrations.AddField(
            model_name='emergencywithdrawalrequest',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_withdrawal_requests', to='university.semestercourse'),
        ),
        migrations.AddField(
            model_name='emergencywithdrawalrequest',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='users.student'),
        ),
        migrations.AddField(
            model_name='reconsiderationrequest',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reconsideration_requests', to='university.semestercourse'),
        ),
        migrations.AddField(
            model_name='reconsiderationrequest',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='users.student'),
        ),
        migrations.AddField(
            model_name='semesterwithdrawalrequest',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semester_withdrawal_requests', to='university.semester'),
        ),
        migrations.AddField(
            model_name='semesterwithdrawalrequest',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='users.student'),
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_courses', to='university.semestercourse'),
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='users.student'),
        ),
        migrations.AlterField(
            model_name='coursecorrectionrequest',
            name='status',
            field=models.CharField(choices=[('A', 'Accepted'), ('R', 'Rejected'), ('I', 'In Progress')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='courseregistrationrequest',
            name='status',
            field=models.CharField(choices=[('A', 'Accepted'), ('R', 'Rejected'), ('I', 'In Progress')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='emergencywithdrawalrequest',
            name='status',
            field=models.CharField(choices=[('A', 'Accepted'), ('R', 'Rejected'), ('I', 'In Progress')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='reconsiderationrequest',
            name='status',
            field=models.CharField(choices=[('A', 'Accepted'), ('R', 'Rejected'), ('I', 'In Progress')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='semesterwithdrawalrequest',
            name='status',
            field=models.CharField(choices=[('A', 'Accepted'), ('R', 'Rejected'), ('I', 'In Progress')], max_length=1, null=True),
        ),
        migrations.CreateModel(
            name='StudentCourseParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('R', 'Registered'), ('A', 'Added'), ('D', 'Dropped')], max_length=1)),
                ('semester_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_semester_course', to='university.semestercourse')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_semester_course', to='student_dash.courseregistrationrequest')),
            ],
        ),
        migrations.AddField(
            model_name='courseregistrationrequest',
            name='courses',
            field=models.ManyToManyField(related_name='registration_requests', through='student_dash.StudentCourseParticipant', to='university.semestercourse'),
        ),
    ]
