# Generated by Django 5.0.3 on 2024-03-20 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_dash', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='advisor',
        ),
        migrations.RemoveField(
            model_name='student',
            name='completed_courses',
        ),
        migrations.RemoveField(
            model_name='student',
            name='courses_in_progress',
        ),
        migrations.RemoveField(
            model_name='student',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='student',
            name='major',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
    ]
