# Generated by Django 5.0.3 on 2024-03-20 06:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_and_time', models.CharField(max_length=100)),
                ('exam_date_and_time', models.DateTimeField()),
                ('exam_location', models.CharField(max_length=100)),
                ('course_capacity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CourseRegistrationRequest',
            fields=[
                ('request_code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('approval_status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DefermentRequest',
            fields=[
                ('request_code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deferment_file', models.FileField(upload_to='deferment_files')),
                ('issuing_authority', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyWithdrawalRequest',
            fields=[
                ('request_code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_outcome', models.CharField(max_length=20)),
                ('student_explanation', models.TextField()),
                ('educational_deputy_explanation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('faculty_code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('faculty_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('major_code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('major_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('number_of_credits', models.PositiveIntegerField()),
                ('degree_level', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ReconsiderationRequest',
            fields=[
                ('request_code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reconsideration_text', models.TextField()),
                ('reconsideration_response', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semester_code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('semester_name', models.CharField(max_length=100)),
                ('course_selection_start_time', models.DateTimeField()),
                ('course_selection_end_time', models.DateTimeField()),
                ('class_start_time', models.DateTimeField()),
                ('class_end_time', models.DateTimeField()),
                ('course_addition_drop_start', models.DateTimeField()),
                ('course_addition_drop_end', models.DateTimeField()),
                ('last_day_for_emergency_withdrawal', models.DateTimeField()),
                ('exam_start_time', models.DateTimeField()),
                ('semester_end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SemesterWithdrawalRequest',
            fields=[
                ('request_code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('withdrawal_outcome', models.CharField(max_length=50)),
                ('student_explanation', models.TextField()),
                ('educational_deputy_explanation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ApprovedCourse',
            fields=[
                ('course_code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
                ('number_of_credits', models.PositiveIntegerField()),
                ('course_type', models.CharField(choices=[('General', 'General'), ('Major', 'Major'), ('Foundation', 'Foundation'), ('Elective', 'Elective')], max_length=20)),
                ('corequisites', models.ManyToManyField(blank=True, related_name='corequisite_for', to='university.approvedcourse')),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='prerequisite_for', to='university.approvedcourse')),
            ],
        ),
        migrations.CreateModel(
            name='CourseCorrectionRequest',
            fields=[
                ('request_code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('approval_status', models.CharField(max_length=20)),
                ('added_courses', models.ManyToManyField(related_name='added_by', to='university.approvedcourse')),
                ('dropped_courses', models.ManyToManyField(related_name='dropped_by', to='university.approvedcourse')),
            ],
        ),
    ]
