# Generated by Django 4.2.10 on 2024-04-07 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Course name in Eng', max_length=100, unique=True)),
                ('units', models.PositiveIntegerField(help_text='Number of units')),
                ('type', models.CharField(choices=[('G', 'General'), ('M', 'Major'), ('F', 'Foundation'), ('E', 'Elective')], help_text="Course Type ('G', 'General'), ('M', 'Major'), ('F', 'Foundation'), ('E', 'Elective')", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Faculty Name', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Major Name', max_length=100, unique=True)),
                ('department', models.CharField(help_text='Major Department', max_length=100)),
                ('units', models.PositiveIntegerField(help_text='Major Units count')),
                ('degree_level', models.CharField(choices=[('AD', "Associate's Degree"), ('BD', "Bachelor's Degree"), ('MD', "Master's Degree"), ('D', 'Doctorate or Ph.D.'), ('PD', 'Professional Degrees')], help_text="Major's Degree Level ('AD', 'Associate's Degree'),\n                    ('BD', 'Bachelor's Degree'), ('MD', 'Master's Degree'),\n                    ('D', 'Doctorate or Ph.D.'),\n                    ('PD', 'Professional Degrees')", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Semester Name', max_length=100)),
                ('course_selection_start_time', models.DateTimeField(help_text='Semester Selection Start Time')),
                ('course_selection_end_time', models.DateTimeField(help_text='Semester Selection End Time')),
                ('class_start_time', models.DateTimeField(help_text='Class Start Time')),
                ('class_end_time', models.DateTimeField(help_text='Class End Time')),
                ('course_addition_drop_start', models.DateTimeField(help_text='Semester Addition Drop Start Time')),
                ('course_addition_drop_end', models.DateTimeField(help_text='Semester Addition Drop End Time')),
                ('last_day_for_emergency_withdrawal', models.DateTimeField(help_text='Last Day For Emergency Withdrawal')),
                ('exam_start_time', models.DateTimeField(help_text='Exam Start Time')),
                ('semester_end_date', models.DateField(help_text='Semester End Time')),
            ],
        ),
        migrations.CreateModel(
            name='SemesterCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_and_time', models.CharField(help_text='Course Day and Time period', max_length=100)),
                ('exam_datetime', models.DateTimeField(help_text='Course Exam Time')),
                ('exam_location', models.CharField(help_text='Course Exam Location', max_length=100)),
                ('capacity', models.PositiveIntegerField(help_text='Course Capacity')),
            ],
        ),
        migrations.CreateModel(
            name='SemesterStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Whether a Student is Active')),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField(help_text='Course Grade')),
                ('course', models.ForeignKey(help_text='Student Course To Student Relation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_courses', to='university.semestercourse')),
            ],
        ),
    ]
