# Generated by Django 4.2.10 on 2024-03-28 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('units', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('G', 'General'), ('M', 'Major'), ('F', 'Foundation'), ('E', 'Elective')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('units', models.PositiveIntegerField()),
                ('degree_level', models.CharField(choices=[('AD', "Associate's Degree"), ('BD', "Bachelor's Degree"), ('MD', "Master's Degree"), ('D', 'Doctorate or Ph.D.'), ('PD', 'Professional Degrees')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course_selection_start_time', models.DateTimeField()),
                ('course_selection_end_time', models.DateTimeField()),
                ('class_start_time', models.DateTimeField()),
                ('class_end_time', models.DateTimeField()),
                ('course_addition_drop_start', models.DateTimeField()),
                ('course_addition_drop_end', models.DateTimeField()),
                ('last_day_for_emergency_withdrawal', models.DateTimeField()),
                ('exam_start_time', models.DateTimeField()),
                ('semester_end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SemesterCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_and_time', models.CharField(max_length=100)),
                ('exam_datetime', models.DateTimeField()),
                ('exam_location', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SemesterStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField()),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_courses', to='university.semestercourse')),
            ],
        ),
    ]
