# Generated by Django 5.0.3 on 2024-03-20 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('university', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecorrectionrequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.student'),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='university.approvedcourse'),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.professor'),
        ),
        migrations.AddField(
            model_name='courseregistrationrequest',
            name='requested_courses',
            field=models.ManyToManyField(blank=True, related_name='course_request', to='university.approvedcourse'),
        ),
        migrations.AddField(
            model_name='courseregistrationrequest',
            name='requesting_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.student'),
        ),
        migrations.AddField(
            model_name='defermentrequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.student'),
        ),
        migrations.AddField(
            model_name='emergencywithdrawalrequest',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='university.approvedcourse'),
        ),
        migrations.AddField(
            model_name='emergencywithdrawalrequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.student'),
        ),
        migrations.AddField(
            model_name='approvedcourse',
            name='offering_faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='university.faculty'),
        ),
        migrations.AddField(
            model_name='major',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='university.faculty'),
        ),
        migrations.AddField(
            model_name='reconsiderationrequest',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='university.approvedcourse'),
        ),
        migrations.AddField(
            model_name='reconsiderationrequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.student'),
        ),
        migrations.AddField(
            model_name='semester',
            name='registered_students_and_professors',
            field=models.ManyToManyField(blank=True, related_name='semesters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='semester',
            name='semester_courses',
            field=models.ManyToManyField(blank=True, related_name='course_semester', to='university.approvedcourse'),
        ),
        migrations.AddField(
            model_name='defermentrequest',
            name='academic_semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='university.semester'),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='academic_semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='university.semester'),
        ),
        migrations.AddField(
            model_name='semesterwithdrawalrequest',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='university.semester'),
        ),
        migrations.AddField(
            model_name='semesterwithdrawalrequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.student'),
        ),
    ]
