# Generated by Django 4.2.10 on 2024-04-07 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourse',
            name='student',
            field=models.ForeignKey(help_text='Student Course To Student Relation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='users.student'),
        ),
        migrations.AddField(
            model_name='semesterstudent',
            name='semester',
            field=models.ForeignKey(help_text='Semester Student to Semester Relation', on_delete=django.db.models.deletion.CASCADE, related_name='semester_students', to='university.semester'),
        ),
        migrations.AddField(
            model_name='semesterstudent',
            name='student',
            field=models.ForeignKey(help_text='Semester Student To Student Relation', on_delete=django.db.models.deletion.CASCADE, related_name='semester_students', to='users.student'),
        ),
        migrations.AddField(
            model_name='semestercourse',
            name='course',
            field=models.ForeignKey(help_text='Semester course To course Relation', on_delete=django.db.models.deletion.CASCADE, related_name='semester_courses', to='university.course'),
        ),
        migrations.AddField(
            model_name='semestercourse',
            name='professor',
            field=models.ForeignKey(help_text='Semester Course To professor Relation', on_delete=django.db.models.deletion.CASCADE, related_name='semester_courses', to='users.professor'),
        ),
        migrations.AddField(
            model_name='semestercourse',
            name='semester',
            field=models.ForeignKey(help_text='Semester course to semester Relation', on_delete=django.db.models.deletion.CASCADE, related_name='semester_courses', to='university.semester'),
        ),
        migrations.AddField(
            model_name='major',
            name='faculty',
            field=models.ForeignKey(help_text='Major Faculty', on_delete=django.db.models.deletion.CASCADE, related_name='majors', to='university.faculty'),
        ),
        migrations.AddField(
            model_name='course',
            name='corequisites',
            field=models.ManyToManyField(blank=True, help_text='Corequisites for a course relation', related_name='corequisite_for', to='university.course'),
        ),
        migrations.AddField(
            model_name='course',
            name='major',
            field=models.ForeignKey(help_text='Course To Major Relation', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='university.major'),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, help_text='Prerequisites for a course relation', related_name='prerequisite_for', to='university.course'),
        ),
    ]
