# Generated by Django 4.2.10 on 2024-04-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourse',
            name='grade',
            field=models.FloatField(default=0, help_text='Course Grade'),
        ),
    ]
