# Generated by Django 4.2.10 on 2024-03-25 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='faculty_name',
            new_name='name',
        ),
    ]
