# Generated by Django 4.2.10 on 2024-04-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestercourse',
            name='exam_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='semestercourse',
            name='exam_location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
