# Generated by Django 4.2.10 on 2024-04-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_alter_semestercourse_exam_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('G', 'General'), ('M', 'Major'), ('F', 'Foundation'), ('E', 'Elective'), ('P', 'Practical')], max_length=20),
        ),
    ]
