# Generated by Django 4.2.10 on 2024-04-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_alter_studentcourse_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='semester_end_date',
            field=models.DateTimeField(help_text='Semester End Time'),
        ),
    ]
