# Generated by Django 4.2.10 on 2024-04-07 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_assistant_major'),
        ('university', '0003_remove_course_faculty_course_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='corequisites',
            field=models.ManyToManyField(blank=True, help_text='Corequisites for a course relation', related_name='corequisite_for', to='university.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='major',
            field=models.ForeignKey(help_text='Course To Major Relation', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='university.major'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(help_text='Course name in Eng', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, help_text='Prerequisites for a course relation', related_name='prerequisite_for', to='university.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('G', 'General'), ('M', 'Major'), ('F', 'Foundation'), ('E', 'Elective')], help_text="Course Type ('G', 'General'), ('M', 'Major'), ('F', 'Foundation'), ('E', 'Elective')", max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='units',
            field=models.PositiveIntegerField(help_text='Number of units'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(help_text='Faculty Name', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='major',
            name='degree_level',
            field=models.CharField(choices=[('AD', "Associate's Degree"), ('BD', "Bachelor's Degree"), ('MD', "Master's Degree"), ('D', 'Doctorate or Ph.D.'), ('PD', 'Professional Degrees')], help_text="Major's Degree Level ('AD', 'Associate's Degree'),\n                    ('BD', 'Bachelor's Degree'), ('MD', 'Master's Degree'),\n                    ('D', 'Doctorate or Ph.D.'),\n                    ('PD', 'Professional Degrees')", max_length=20),
        ),
        migrations.AlterField(
            model_name='major',
            name='department',
            field=models.CharField(help_text='Major Department', max_length=100),
        ),
        migrations.AlterField(
            model_name='major',
            name='faculty',
            field=models.ForeignKey(help_text='Major Faculty', on_delete=django.db.models.deletion.CASCADE, related_name='majors', to='university.faculty'),
        ),
        migrations.AlterField(
            model_name='major',
            name='name',
            field=models.CharField(help_text='Major Name', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='major',
            name='units',
            field=models.PositiveIntegerField(help_text='Major Units count'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='class_end_time',
            field=models.DateTimeField(help_text='Class End Time'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='class_start_time',
            field=models.DateTimeField(help_text='Class Start Time'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='course_addition_drop_end',
            field=models.DateTimeField(help_text='Semester Addition Drop End Time'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='course_addition_drop_start',
            field=models.DateTimeField(help_text='Semester Addition Drop Start Time'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='course_selection_end_time',
            field=models.DateTimeField(help_text='Semester Selection End Time'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='course_selection_start_time',
            field=models.DateTimeField(help_text='Semester Selection Start Time'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='exam_start_time',
            field=models.DateTimeField(help_text='Exam Start Time'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='last_day_for_emergency_withdrawal',
            field=models.DateTimeField(help_text='Last Day For Emergency Withdrawal'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.CharField(help_text='Semester Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester_end_date',
            field=models.DateField(help_text='Semester End Time'),
        ),
        migrations.AlterField(
            model_name='semestercourse',
            name='capacity',
            field=models.PositiveIntegerField(help_text='Course Capacity'),
        ),
        migrations.AlterField(
            model_name='semestercourse',
            name='course',
            field=models.ForeignKey(help_text='Semester course To course Relation', on_delete=django.db.models.deletion.CASCADE, related_name='semester_courses', to='university.course'),
        ),
        migrations.AlterField(
            model_name='semestercourse',
            name='day_and_time',
            field=models.CharField(help_text='Course Day and Time period', max_length=100),
        ),
        migrations.AlterField(
            model_name='semestercourse',
            name='exam_datetime',
            field=models.DateTimeField(help_text='Course Exam Time'),
        ),
        migrations.AlterField(
            model_name='semestercourse',
            name='exam_location',
            field=models.CharField(help_text='Course Exam Location', max_length=100),
        ),
        migrations.AlterField(
            model_name='semestercourse',
            name='professor',
            field=models.ForeignKey(help_text='Semester Course To professor Relation', on_delete=django.db.models.deletion.CASCADE, related_name='semester_courses', to='users.professor'),
        ),
        migrations.AlterField(
            model_name='semestercourse',
            name='semester',
            field=models.ForeignKey(help_text='Semester course to semester Relation', on_delete=django.db.models.deletion.CASCADE, related_name='semester_courses', to='university.semester'),
        ),
        migrations.AlterField(
            model_name='semesterstudent',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether a Student is Active'),
        ),
        migrations.AlterField(
            model_name='semesterstudent',
            name='semester',
            field=models.ForeignKey(help_text='Semester Student to Semester Relation', on_delete=django.db.models.deletion.CASCADE, related_name='semester_students', to='university.semester'),
        ),
        migrations.AlterField(
            model_name='semesterstudent',
            name='student',
            field=models.ForeignKey(help_text='Semester Student To Student Relation', on_delete=django.db.models.deletion.CASCADE, related_name='semester_students', to='users.student'),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='course',
            field=models.ForeignKey(help_text='Student Course To Student Relation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_courses', to='university.semestercourse'),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='grade',
            field=models.FloatField(help_text='Course Grade'),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='student',
            field=models.ForeignKey(help_text='Student Course To Student Relation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='users.student'),
        ),
    ]
